### ISSUE TITLE
BellaBeat - Capstone Project by Google

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#248] opened 2022-07-10 08:50 UTC
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : BellaBeat - Capstone Project by Google
:red_circle: **Aim** : The aim of this project is to create a model which will analyze the Bellabeat project.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/dafertflores/google-capstone-project-bellabeat
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment] 2022-07-10 08:51
Or you can use this dataset too for this project, https://www.kaggle.com/datasets/carlodipaola/bellabeat-dataset

**Comment by BhardwajArjit** [comment] 2023-12-14 10:07
I am interested to contribute in this project, please assign it to me.
Full name : Arjit Bhardwaj
GitHub Profile Link : https://github.com/BhardwajArjit
Participant ID: NA
Approach for this Project : First I will do the Exploratory Data Analysis to become one with data. Then I will implement some classification algorithms like Logistic Regression, Decision Trees and  Random Forest to analysis the health outlook and also to predict it too.
Participant Role : KWOC

**Comment by abhisheks008** [comment] 2023-12-14 13:28
Issue assigned to you @BhardwajArjit

**Comment by abhisheks008** [comment] 2023-12-20 13:15
Hi @BhardwajArjit any update on this issue?

**Comment by BhardwajArjit** [comment] 2023-12-20 13:38
Hi Abhishek,

I have created the pull request, kindly review it.

**Closed** 2024-01-02 06:03 UTC
Labels: Assigned :computer:, KWOC 2023

**Comment by BhardwajArjit** [comment] 2024-01-02 10:15
Hi Abhishek,

That's great to know. I would thank you for being so patient and
cooperative with me throughout this project.

Lastly, I have one doubt regarding KWoC. I have contributed only to this
project which includes only 1 PR, so am I qualified for KWoC, since it
mentions we should have at least 2 PRs for end evals?
