### ISSUE TITLE
Engineering Graduate Salary Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#156] opened 2022-02-01 07:24 UTC
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Engineering Graduate Salary Prediction
:red_circle: **Aim** : Predict The Salary of An Indian Engineering Graduate
:red_circle: **Dataset** : https://www.kaggle.com/manishkc06/engineering-graduate-salary-prediction
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by dilroseR** [comment] 2022-02-02 07:04
I would like to work on this under JWOC. @abhisheks008

**Comment by abhisheks008** [comment] 2022-02-02 07:17
Issue assigned to you @dilroseR

**Comment by abhisheks008** [comment] 2022-02-04 07:34
What's the update here @dilroseR

**Comment by dilroseR** [comment] 2022-02-04 08:11
> What's the update here @dilroseR

Please give the problem to someone else. Stuck with some other problem!

**Comment by abhisheks008** [comment] 2022-02-04 08:43
Okay! This issue is unassigned from you @dilroseR

**Comment by aswinikalyan30** [comment] 2022-04-06 11:25
Full name : Aswini Kalyan
GitHub Profile Link :https://github.com/aswinikalyan30
Approach for this Project : Regression algorithms
What is your participant role?

- [ ]  - SWOC 2.0 Participant.
- [ ]  - JWOC 2022 Participant.
- [x]  - Contributor (OpenCode)

**Comment by abhisheks008** [comment] 2022-04-06 13:17
Issue assigned to you @aswinikalyan30. Go ahead! 🚀

**Comment by abhisheks008** [comment] 2022-04-11 04:15
@aswinikalyan30 what's the progress on this issue?

**Comment by aswinikalyan30** [comment] 2022-04-11 06:11
Hey, I dont feel i cant do this.. can you unassign it from me?

**Comment by LahariBoni** [comment] 2022-07-21 18:29
Hi @abhisheks008 , I would like to work on this issue. Could you please assign this to me.

Full name: Lahari Boni

GitHub Profile Link: https://github.com/LahariBoni

Participant ID:  N/A

Approach for this Project: Firstly, I'd like to perform basic exploration on the data and clean it if necessary. After that, I will try to draw conclusions from the dataset and find insights in relation to the target variable. Finally, I am planning to experiment with various supervised algorithms like linear regression, lasso regression, etc. and compare accuracies to see which model best fits the data.

Participant role: HSOC Participant

**Comment by abhisheks008** [comment] 2022-07-22 03:43
Issue assigned to you @LahariBoni

**Comment by abhisheks008** [comment] 2022-08-02 08:06
Hey @LahariBoni updates please.

**Comment by LahariBoni** [comment] 2022-08-02 08:11
> Hey @LahariBoni updates please.

Hi @abhisheks008, I am really sorry that I took so long. Due to unavoidable reasons, I am not able to work on this for a while. Could you please give me 3-4 more days of time to make pr.

**Comment by abhisheks008** [comment] 2022-08-03 04:52
Hey @LahariBoni, thanks for the update. No worries, take your time and keep updating here or in the Discord channel.

**Comment by LahariBoni** [comment] 2022-08-03 04:56
> Hey @LahariBoni, thanks for the update. No worries, take your time and keep updating here or in the Discord channel.

Sure @abhisheks008, thank you.

**Comment by abhisheks008** [comment] 2022-08-06 08:37
Updates please @LahariBoni

**Comment by LahariBoni** [comment] 2022-08-07 11:30
Hello @abhisheks008, worked on linear regression and trying to experiment with few more. After that I will work on final version with comments and markdowns and then make a PR in the next 2-3 days. Sorry for being late Abhishek.

**Comment by abhisheks008** [comment] 2022-08-13 08:12
@LahariBoni any updates?

**Comment by abhisheks008** [comment] 2022-08-30 07:47
Please complete the issue before the deadline @LahariBoni

**Comment by LahariBoni** [comment] 2022-09-09 09:03
> Please complete the issue before the deadline @LahariBoni

Hello @abhisheks008. I tried my best to complete it but due to some circumstances I was not able to do so. I am really sorry for this Abhishek.

**Comment by Satyawan7** [comment] 2022-09-14 06:05
Full name : Satyawan Bhuyan
GitHub Profile Link :https://github.com/Satyawan7
Approach for this Project : Regression algorithms
What is your participant role?
Contributor

**Comment by abhisheks008** [comment] 2022-09-14 08:11
Are you contributing here via any open source program? @Satyawan7

**Comment by TabishMomin** [comment] 2022-10-05 14:23
I would likes to contribute in these project

**Comment by TabishMomin** [comment] 2022-10-05 14:24
I would like to contribute in these project

**Comment by TabishMomin** [comment] 2022-10-06 17:26
Full name : Tabish Momin

GitHub Profile Link : https://github.com/TabishMomin

Approach for this Project : Linear regression , RandomForestRegressor

What is your participant role:  Contributor

**Comment by abhisheks008** [comment] 2022-10-12 08:19
Try to implement as much algorithms as you know. It will be better for checking and comparing the accuracies to get the best fitted model for this dataset/project.

Issue assigned to @TabishMomin

**Closed** 2022-10-13 16:14 UTC
Labels: Assigned :computer:, Contributors
