### ISSUE TITLE
MS COCO dataset

### ISSUE THREAD

**Issue by ASLManasa** [abhisheks008/ML-Crate#52] opened 2021-12-25 08:23 UTC
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : MS COCO dataset
:red_circle: **Aim** : TTo detect objects from the image and then generate captions for them. LSTM (Long short term memory) network is responsible for generating sentences in English and CNN is used to extract features from image. To build a caption generator we have to combine these two models.
:red_circle: **Dataset** : https://www.kaggle.com/awsaf49/coco-2017-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by karishni** [comment] 2021-12-25 11:21
Full name : Karishni Mehta
GitHub Profile Link : https://github.com/karishni
Participant ID : 466
Approach for this Project : Combine the LSTM model with CNN (please let me know if there are other ways to do it)
Are you a participant of SWOC 2.0?
 YES

**Comment by abhisheks008** [comment] 2021-12-25 16:09
Issue assigned to you @karishni

**Comment by karishni** [comment] 2021-12-30 16:36
I would like to work on the flickr8k (https://www.kaggle.com/adityajn105/flickr8k) dataset instead of ms coco

**Comment by ASLManasa** [comment] 2021-12-31 03:22
@karishni okay go ahead.

**Comment by sankalp-srivastava** [comment] 2022-01-01 03:28
This is duplicate of caption generation from images

**Comment by sankalp-srivastava** [comment] 2022-01-01 03:28
@abhisheks008

**Comment by ASLManasa** [comment] 2022-01-01 04:27
@sankalp-srivastava  the dataset is very large(28gb) hence she has taken a  smaller one.

**Comment by abhisheks008** [comment] 2022-01-01 04:41
@sankalp-srivastava Don't worry, as she is going to use a different dataset, let's check the accuracy and it will also make a comparison of the two datasets.

**Comment by abhisheks008** [comment] 2022-01-05 04:42
@karishni What's the update here for this project?

**Comment by karishni** [comment] 2022-01-05 17:40
I’m working on it, had some issue with my laptop due to which I couldn’t work for a few day, sorry for the delay

**Comment by abhisheks008** [comment] 2022-01-21 14:44
@karishni ?

**Comment by karishni** [comment] 2022-01-22 05:46
@abhisheks008 Hey, I had messaged you stating that my exams are going on and won’t be able to complete this till the end of the month, but this will be done by the end of next week

**Comment by abhisheks008** [comment] 2022-01-22 05:51
OKAY!

**Comment by karishni** [comment] 2022-02-01 06:45
I'm done with this issue, had a doubt, what should I name the folder as the name of the issue is MS COCO dataset but I'm using the flickr8k dataset

**Comment by abhisheks008** [comment] 2022-02-01 06:55
Name the folder as, `FLICKR8k Dataset Analysis (MS COCO)`

@karishni

**Closed** 2022-02-02 03:42 UTC
Labels: Assigned :computer:, SWOC 2021
