### ISSUE TITLE
House Price Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#7] opened 2021-12-11 14:18 UTC
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : House Price Prediction
:red_circle: **Aim** : Predict the housing prices of a new house using linear regression. Linear regression is used to predict values of unknown input when the data has some linear relationship between input and output variables.
:red_circle: **Dataset** : https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Vanshikagoel0012** [comment] 2021-12-12 08:09
Full name : Vanshika goel
GitHub Profile Link :https://github.com/Vanshikagoel0012
Participant ID :1093
Approach for this Project House Price Prediction #7
Are you a participant of SWOC 2.0?
YES

**Comment by abhisheks008** [comment] 2021-12-12 08:16
@Vanshikagoel0012 Tell me what are the algorithms you are going to use?

**Comment by Vanshikagoel0012** [comment] 2021-12-12 08:21
This will be based on linear regression

**Comment by abhisheks008** [comment] 2021-12-12 08:58
@Vanshikagoel0012 Try to implement more regression algorithms like decision tree, random forest, gradient boosting and many more. Then make a comparison of all the algorithms based on the accuracy scores, f1 score, r2 score and finalize the best fitted model/algorithm.

Anyways the issue is assigned to you, go ahead!

**Comment by Vanshikagoel0012** [comment] 2021-12-12 10:36
okayy

**Comment by ASLManasa** [comment] 2021-12-21 06:35
@Vanshikagoel0012 update?

**Comment by Vanshikagoel0012** [comment] 2021-12-21 17:40
will upload it by tomorrow.

**Comment by abhisheks008** [comment] 2021-12-27 03:56
Hey @Vanshikagoel0012, what's the update here?

**Comment by Vanshikagoel0012** [comment] 2021-12-27 07:28
The dataset above can only be opened in UNIX operating system I have also messaged @abhisheks008  regarding this on discord.

**Comment by abhisheks008** [comment] 2021-12-30 07:45
@Vanshikagoel0012 sorry for the inconvenience caused from my side. You can use a suitable dataset as pe your choice to complete this project. No issues.

**Comment by Vanshikagoel0012** [comment] 2021-12-30 08:36
No problem,I will use the dataset according to my convenience

**Comment by abhisheks008** [comment] 2021-12-30 10:28
Yup go ahead @Vanshikagoel0012

**Comment by Vanshikagoel0012** [comment] 2022-01-12 04:25
DUE TO SOME PERSONAL REASON I WAS NOT ABLE TO FOCUS ON THAT PLEASE REASSIGN ME THIS
HOUSE PRICE PREDICTION MODEL
I HAVE COMPLETED IT  I JUST NEED TO MAKE SOME EDITS

**Comment by abhisheks008** [comment] 2022-01-12 05:59
I know everyone is having their personal problems, but it's your responsibility to provide an update to us, otherwise how can we assess your situation and all?

Anyways assigning to you again and make a fresh PR for this issue, also follow the proper folder distribution for the project.

@Vanshikagoel0012

**Comment by Vanshikagoel0012** [comment] 2022-01-12 06:11
Thank you so much for understanding

**Closed** 2022-01-15 04:17 UTC
Labels: Assigned :computer:, SWOC 2021
